In [2]:
import os


In [3]:
from keras.preprocessing import image

In [4]:
import pandas as pd


In [5]:
import cv2

In [6]:
categories = ['with_mask','without_mask']

In [7]:
data = []
for category in categories:
    path = os.path.join('train',category)
    
    label = categories.index(category)
    
    for file in os.listdir(path):
#         print(file)
        img_path = os.path.join(path,file)
        img = cv2.imread(img_path)
        img = cv2.resize(img,(224,224))
        
        data.append([img,label])

#         print(img.shape)
#         print(img_path)
        
#     print(path)

In [8]:
len(data)

1279

In [9]:
import random

In [10]:
random.shuffle(data)

In [11]:
x = []
y = []

for features,label in data:
    x.append(features)
    y.append(label)

In [12]:
len(x)
len(y)

1279

In [13]:
import numpy as np

In [14]:
x = np.array(x)
y= np.array(y)

In [15]:
x.shape

(1279, 224, 224, 3)

In [16]:
y.shape

(1279,)

In [16]:
y

array([0, 1, 1, ..., 1, 1, 1])

In [17]:
x

array([[[[154, 206, 229],
         [154, 206, 229],
         [155, 209, 232],
         ...,
         [184, 217, 229],
         [158, 184, 194],
         [ 31,  50,  54]],

        [[161, 209, 233],
         [159, 209, 232],
         [160, 211, 234],
         ...,
         [188, 220, 233],
         [158, 184, 194],
         [ 31,  50,  54]],

        [[162, 206, 230],
         [160, 206, 230],
         [160, 208, 232],
         ...,
         [187, 219, 232],
         [158, 184, 194],
         [ 31,  50,  54]],

        ...,

        [[  5,  38,  27],
         [ 16,  43,  33],
         [ 46,  63,  54],
         ...,
         [216, 219, 240],
         [172, 181, 189],
         [ 39,  48,  48]],

        [[ 15,  47,  38],
         [ 24,  49,  41],
         [ 45,  61,  54],
         ...,
         [209, 212, 233],
         [164, 173, 182],
         [ 39,  47,  49]],

        [[ 27,  60,  53],
         [ 35,  63,  57],
         [ 45,  61,  57],
         ...,
         [204, 207, 228],
        

In [17]:
x = x/154

In [19]:
x

array([[[[1.        , 1.33766234, 1.48701299],
         [1.        , 1.33766234, 1.48701299],
         [1.00649351, 1.35714286, 1.50649351],
         ...,
         [1.19480519, 1.40909091, 1.48701299],
         [1.02597403, 1.19480519, 1.25974026],
         [0.2012987 , 0.32467532, 0.35064935]],

        [[1.04545455, 1.35714286, 1.51298701],
         [1.03246753, 1.35714286, 1.50649351],
         [1.03896104, 1.37012987, 1.51948052],
         ...,
         [1.22077922, 1.42857143, 1.51298701],
         [1.02597403, 1.19480519, 1.25974026],
         [0.2012987 , 0.32467532, 0.35064935]],

        [[1.05194805, 1.33766234, 1.49350649],
         [1.03896104, 1.33766234, 1.49350649],
         [1.03896104, 1.35064935, 1.50649351],
         ...,
         [1.21428571, 1.42207792, 1.50649351],
         [1.02597403, 1.19480519, 1.25974026],
         [0.2012987 , 0.32467532, 0.35064935]],

        ...,

        [[0.03246753, 0.24675325, 0.17532468],
         [0.1038961 , 0.27922078, 0.21428571]

In [18]:
from sklearn.model_selection import train_test_split
x_train , x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [19]:
x_train.shape

(1023, 224, 224, 3)

In [20]:
x_test.shape

(256, 224, 224, 3)

In [21]:
from keras.applications.vgg16 import VGG16

In [22]:
vgg = VGG16()

553467096/553467096 [==============================] - 113s 0us/step


In [23]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [24]:
# last wala layer hatane ke liye
from keras import Sequential 

In [26]:
model = Sequential()

In [27]:
for layer in vgg.layers[:-1]:
    model.add(layer)

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [32]:
# layer ko freeze krenge taki run krne pe update na ho to uske liye

for layer in model.layers:
    layer.trainable = False

In [33]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [34]:
from keras.layers import Dense

In [36]:
model.add(Dense(1,activation = 'sigmoid'))

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0         
                                                                 
 block3_conv1 (Conv2D)       (None, 56, 56, 256)       2

In [38]:
model.compile(optimizer = 'Adam' , loss = 'binary_crossentropy',metrics = ['accuracy'])

In [39]:
model.fit(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
32/32 [==============================] - 641s 18s/step - loss: 0.4172 - accuracy: 0.8426 - val_loss: 0.2795 - val_accuracy: 0.9180
Epoch 2/5
32/32 [==============================] - 395s 12s/step - loss: 0.2003 - accuracy: 0.9570 - val_loss: 0.1795 - val_accuracy: 0.9609
Epoch 3/5
32/32 [==============================] - 392s 12s/step - loss: 0.1442 - accuracy: 0.9648 - val_loss: 0.1472 - val_accuracy: 0.9648
Epoch 4/5
32/32 [==============================] - 381s 12s/step - loss: 0.1287 - accuracy: 0.9648 - val_loss: 0.1226 - val_accuracy: 0.9648
Epoch 5/5
32/32 [==============================] - 388s 12s/step - loss: 0.1075 - accuracy: 0.9736 - val_loss: 0.1094 - val_accuracy: 0.9727


In [53]:
cap = cv2.VideoCapture(0)

In [118]:
while True:
    ret,frame = cap.read()
    
#     call the detection method


    img = cv2.resize(frame,(224,224))
    y_pred = detect_face_mask(img)
#     print(y_pred)

    coods = detect_face(cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY))
    
    for x,y,w,h in coods:
        cv2.rectangle(frame,(x,y),(x+w,x+h),(255,0,0),3)

    if y_pred == 0:
        draw_label(frame,"mask",(30,30),(0,255,0))
    else:
        draw_label(frame,"NO mask",(30,30),(0,0,255))
    
#     draw_label(frame,"Face Mask Detection",(30,30),(255,0,0))
    
    cv2.imshow("window",frame)
    
    if cv2.waitKey(1) & 0xFF == ord('x'):     
        
        break
                                    
cv2.destroyAllWindows()

1/1 [==============================] - 0s 473ms/step


In [94]:
def detect_face_mask(img):
    y_pred = model.predict(img.reshape(1,224,224,3))
    return y_pred

In [89]:
def draw_label(img,text,pos,bg_color):
    
    text_size = cv2.getTextSize(text,cv2.FONT_HERSHEY_SIMPLEX,1,cv2.FILLED)
    
    end_x = pos[0] + text_size[0][0]+2
    end_y = pos[0] + text_size[0][0]-2
    
    cv2.rectangle(img,pos,(end_x,end_y),bg_color,cv2.FILLED)
    
    cv2.putText(img,text,pos,cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,0),1,cv2.LINE_AA)

In [117]:
while True:
    
    ret,frame = cap.read()
    
    coods = detect_face(cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY))
    
    for x,y,w,h in coods:
        cv2.rectangle(frame,(x,y),(x+w,x+h),(255,0,0),3)
    
    
    cv2.imshow("window",frame)
    
    if cv2.waitKey(1) & 0xFF == ord('x'):
        break
cv2.destroyAllWindows()

In [113]:
haar = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# yha pe ek problem aayi thi jo mene stackover flow se solove ki thi
# https://stackoverflow.com/questions/30508922/error-215-empty-in-function-detectmultiscale 
# yha dekhe haar = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml') ye pahle
# haar = cv2.CascadeClassifier('haarcascade_frontalface_default.xml') ese likha tha


In [115]:
def detect_face(img):
    
    coods = haar.detectMultiScale(img)
    
    return coods